baseurl: "https://wizardunicorn.ninja"
title: Wizard Unicorn Ninja
description: Frontend Development Worknotes and Resources, brought to you by William Harrison.
theme: null
destination: docs

# GitHub information
# This is used for adding an edit this page link to the footer
github_info:
  repository: wizardunicorn.ninja
  default_branch: main

# Configuration for Google Analytics
google_analytics_ua: UA-183755378-1

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  block:
    line_numbers: true
    start_line: 1

plugins:
  - jekyll-postcss

exclude: [build, vendor, node_modules]