name: Build and deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  react: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch âœ…
        uses: actions/checkout@v2
      # Install Node
      - name: Setup Node ğŸ–¥
        uses: actions/setup-node@v1
        with:
          node-version: 'v12.12.0'
      # Build React App from Complete Intro to React workshop
      - name: Build React App from Complete Intro to React workshop
        run: complete-intro-react/adopt-me/build.sh

  jekyll:
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout main branch âœ…
        uses: actions/checkout@v2
      # Install Ruby to be able to build the site using Jekyll
      - name: Setup Ruby ğŸ’
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
          bundler-cache: true
      # Install Node
      - name: Setup Node ğŸ–¥
        uses: actions/setup-node@v1
        with:
          node-version: 'v12.12.0'
      # Build site & Run PurgeCSS
      - name: Build Jekyll & Run PurgeCSS
        run: test/build.sh
      # Make CNAME record for Github Deployment to custom domain
      - name: Make CNAME File ğŸ“„
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "./CNAME"
          FILE_DATA: "wizardunicorn.ninja"
      # Push the compiled _site-folder as (dev) branch into your GitHub repository
      - name: Deploy to GitHub Pages ğŸ£
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: dev