name: Build and deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout main branch ‚úÖ
        uses: actions/checkout@v2
      # Install Ruby to be able to build the site using Jekyll
      - name: Setup Ruby üíé
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
          bundler-cache: true
      # Install Node
      - name: Setup Node üñ•
        uses: actions/setup-node@v1
        with:
          node-version: 'v12.12.0'
      # Install Node Modules for React Workshop Project Build React
      - name: Install Node Modules for React Workshop Project
        run: npm install
        working-directory: complete-intro-react/adopt-me
      # Build React
      - name: Build React
        run: npm run prod
        working-directory: complete-intro-react/adopt-me
      # Build site & Run PurgeCSS
      - name: Build Jekyll & Run PurgeCSS
        run: test/build.sh
        working-directory: ./test
      # Make CNAME record for Github Deployment to custom domain
      - name: Make CNAME File üìÑ
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "./CNAME"
          FILE_DATA: "wizardunicorn.ninja"
      # Push the compiled _site-folder as (dev) branch into your GitHub repository
      - name: Deploy to GitHub Pages üê£
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: dev